# Generated by Django 5.1.1 on 2024-10-04 09:51

import sports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_remove_user_email_remove_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True, validators=[sports.models.validate_min_length]),
        ),
    ]
