# Generated by Django 5.1.1 on 2024-10-09 05:36

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('username'), name='unique_upper_username'),
        ),
    ]
